//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProviderApp.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDevice
    {
        public int RequestID { get; set; }
        public int DeviceID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Request Request { get; set; }
    }
}
